name: tests

on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v2

      # 2. Install dependencies
      # - name: Install dependencies
      #   run: |
      #     apt-get update                                  &&  \
      #     apt-get upgrade -y                              &&  \
      #     apt-get install -y python3-pip

      # 3. Run test
      - name: Run test
        run: |
          ./test.py